name: PETS_app
options:
  bundleIdPrefix: com.jeffwhite
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"
  preserveUserSettings: true
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.0.0
targets:
  PETS_app:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jeffwhite.petapp
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: false
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_CFBundleURLTypes: 
          - CFBundleURLSchemes: 
            - com.googleusercontent.apps.1-672591439997-ios-4c8d078907da4e46376914
        OTHER_LDFLAGS: $(inherited) -ObjC
        SWIFT_INSTALL_OBJC_HEADER: NO
        CLANG_ENABLE_MODULES: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        ENABLE_TESTABILITY: YES
        ONLY_ACTIVE_ARCH: YES
        VALIDATE_WORKSPACE: YES
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseAnalytics
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
    info:
      path: Sources/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        NSLocationWhenInUseUsageDescription: "We need your location to find nearby study groups and learning resources."
        NSLocationAlwaysAndWhenInUseUsageDescription: "We need your location to find nearby study groups and learning resources."
        NSCameraUsageDescription: "We need camera access to let you share photos with your study groups."
        NSPhotoLibraryUsageDescription: "We need photo library access to let you share photos with your study groups." 