name: PETS_app
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 17.0
    macOS: 14.0
    tvOS: 17.0
    visionOS: 1.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "10.0.0"
targets:
  PETS_app:
    type: application
    platform: iOS
    sources:
      - path: PETS_app
    resources:
      - path: PETS_app/GoogleService-Info.plist
    settings:
      base:
        INFOPLIST_FILE: PETS_app/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.PETS_app
        DEVELOPMENT_TEAM: TTTFBZBMNC
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: Apple Development
        SWIFT_VERSION: 5.0
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        ENABLE_BITCODE: NO
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseDatabase
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseStorage
    info:
      path: PETS_app/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight 